### ISSUE TITLE
Ruby 2 and foreman signals 

### ISSUE THREAD

**Issue by divoxx** [ddollar/foreman#332]
Looks like Ruby 2.0 does not allow synchronizing inside a trap context and foreman fail to terminate processes, leaving zombies behind.

```
^CSIGINT received
/Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:230:in `synchronize': can't be called from trap context (ThreadError)
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:230:in `output_with_mutex'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:236:in `system'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:313:in `terminate_gracefully'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:45:in `block in start'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:298:in `call'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:298:in `wait2'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:298:in `watch_for_termination'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/engine.rb:52:in `start'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/lib/foreman/cli.rb:41:in `start'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/foreman-0.61.0/bin/foreman:7:in `<top (required)>'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/bin/foreman:23:in `load'
    from /Users/divoxx/.rbenv/versions/2.0.0-p0/bin/foreman:23:in `<main>'
```

**Comment by Geesu** [comment]
+1
