### ISSUE TITLE
require "dotenv" left behind in engine.rb after recent change

### ISSUE THREAD

**Issue by jimflood** [ddollar/foreman#547]
After $ bundle install --clean you will hit:

Uncaught exception: cannot load such file -- dotenv
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/lib/foreman/engine.rb:4:in `require'
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/lib/foreman/engine.rb:4:in `<top (required)>'
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/lib/foreman/cli.rb:3:in `require'
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/lib/foreman/cli.rb:3:in `<top (required)>'
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/bin/foreman:5:in `require'
	/home/jim/.rvm/gems/ruby-2.1.5@hinode/gems/foreman-0.77.0/bin/foreman:5:in `<top (required)>'

**Comment by jimflood** [comment]
oops my mistake
