### ISSUE TITLE
`method_missing': undefined method `this'

### ISSUE THREAD

**Issue by abrambailey** [ddollar/foreman#662]
This just started randomly this morning on foreman start. Everything was fine yesterday.
```
.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2157:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fefa8813134 foreman-0.82.0> (NoMethodError)
  from .rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1056:in `find_active_stub_by_path'
  from .rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:63:in `require'
  from .rvm/gems/ruby-2.2.1/gems/foreman-0.82.0/bin/foreman:5:in `<top (required)>'
  from .rvm/gems/ruby-2.2.1/bin/foreman:23:in `load'
  from .rvm/gems/ruby-2.2.1/bin/foreman:23:in `<main>'
  from .rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
  from .rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Alxzu** [comment]
Same here

**Comment by abrambailey** [comment]
I fixed this by updating rails and ruby (not sure which was the culprit) to:
```
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
Rails 4.2.7
```

**Comment by NaixSpirit** [comment]
+1
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
Rails 5.0.1
