### ISSUE TITLE
config/unicorn.rb not found

### ISSUE THREAD

**Issue by dmkc** [ddollar/foreman#677]
Hi! We're having a path related issue w unicorn not finding its config. Here's the output of foreman I get running `foreman start -c all=1`:
```
10:54:46 scheduler_clock.1        | started with pid 14176
10:54:47 web.1                    | I, [2017-05-04T10:54:47.439530 #14172]  INFO -- : listening on addr=0.0.0.0:5000 fd=11
10:54:47 web.1                    | I, [2017-05-04T10:54:47.439700 #14172]  INFO -- : worker=0 spawning...
10:54:47 web.1                    | I, [2017-05-04T10:54:47.441198 #14172]  INFO -- : master process ready
10:54:47 web.1                    | I, [2017-05-04T10:54:47.442377 #14177]  INFO -- : worker=0 spawned pid=14177
10:54:47 web.1                    | I, [2017-05-04T10:54:47.442955 #14177]  INFO -- : Refreshing Gem list
10:54:47 web.1                    | bundler: failed to load command: unicorn (/Users/dmkc/.gem/ruby/2.3.3/bin/unicorn)
10:54:47 web.1                    | LoadError: cannot load such file -- config/unicorn.rb
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn.rb:58:in `require'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn.rb:58:in `block in builder'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:752:in `build_app!'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:617:in `init_worker_process'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:639:in `worker_loop'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
10:54:47 web.1                    |   /Users/dmkc/.gem/ruby/2.3.3/bin/unicorn:23:in `load'
```

Unicorn starts up fine if I run it directly with `bundle exec unicorn -c config/unicorn.rb`. I've tried adding a `puts Dir.pwd` statement inside my  `~/.gem/ruby/2.3.1/bin/foreman` to make sure the path looks correct, and it does. I'm on unicorn 5.2.0, bundler 1.15.0.pre.3, ruby 2.3.3, foreman 0.84, OS X 10.12.4.

I'm a little stumped on how to debug this. Any help would be appreciated :).

**Comment by ddollar** [comment]
Do you have a PATH or some other environment variable that is affecting it?

Going to close this as it's unlikely to be a problem with Foreman.
