### ISSUE TITLE
foreman fails to start on linux with LoadError: io/console (again)

### ISSUE THREAD

**Issue by tai2** [ddollar/foreman#694]
Is this a regression to [this state](https://github.com/ddollar/foreman/issues/442)?

forman version: 0.84.0

```sh
/app # uname -a
Linux c9df8988a7da 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 Linux
/app # ruby -v
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux-musl]
/app # bundle exec foreman start
bundler: failed to load command: foreman (/usr/bin/foreman)
LoadError: cannot load such file -- io/console
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/color.rb:1:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/color.rb:1:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell.rb:17:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell.rb:17:in `shell'
  /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:439:in `start'
  /usr/lib/ruby/gems/2.3.0/gems/foreman-0.82.0/bin/foreman:7:in `<top (required)>'
  /usr/bin/foreman:22:in `load'
  /usr/bin/foreman:22:in `<top (required)>'
/app #
```

**Comment by andrewmcodes** [comment]
@tai2 is this still an issue?

**Comment by tai2** [comment]
I forgot what the environment was and where it was at that time.
So I tried to build near environment as much as possible.
The result is that foreman run successfully.

https://github.com/tai2/foreman-issue-694
