### ISSUE TITLE
"Foreman s" throws an error on windows

### ISSUE THREAD

**Issue by Hafid24** [ddollar/foreman#733]
I am setting up a development environment but when I run `foreman s` I get this error:
`C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/process.rb:54:in `spawn': Exec format error - ./bin/webpack-dev-server (Errno::ENOEXEC)
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/process.rb:54:in `block in run'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/process.rb:53:in `chdir'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/process.rb:53:in `run'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:367:in `block (2 levels) in spawn_processes'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:364:in `upto'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:364:in `block in spawn_processes'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:363:in `each'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:363:in `spawn_processes'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/engine.rb:57:in `start'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/lib/foreman/cli.rb:42:in `start'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/foreman-0.85.0/bin/foreman:7:in `<top (required)>'
        from C:/tools/ruby24/bin/foreman:23:in `load'
        from C:/tools/ruby24/bin/foreman:23:in `<main>'
`

**Comment by Hafid24** [comment]
@brixen

**Comment by kuyenda** [comment]
``how to solve that? Same problem occurs even only generating a new default application.
on git bash
`$ bin/dev
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/foreman-0.87.2/lib/foreman/process.rb:54:in `spawn': Exec format error - bin/rails server -p 3000 (Errno::ENOEXEC)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/foreman-0.87.2/lib/foreman/process.rb:54:in `block in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/foreman-0.87.2/lib/foreman/process.rb:53:in `chdir'`

**$ foreman check -f Procfile.dev
valid procfile detected (web, css)**

in ./Procfile.dev
`web: bin/rails server -p 3000 -b '0.0.0.0'
css: bin/rails tailwindcss:watch`

**Comment by jwisener** [comment]
I get the same issue.

**Comment by mirouhml** [comment]
Same issue.. I can't use tailwindcss because of it.

**Comment by sachalchandio** [comment]
rails is fucking hilarious, someday I hope someday they stop working on shit like coffeeScript and stimulus.

**Comment by charliebeveridge** [comment]
this command fixes it for me: tailwindcss -i app/assets/stylesheets/application.tailwind.css -o app/assets/builds/tailwind.css -c config/tailwind.config.js -w

from here: https://github.com/rails/tailwindcss-rails/issues/118
