### ISSUE TITLE
Error after running command "foreman start"

### ISSUE THREAD

**Issue by vasilevskykv** [ddollar/foreman#793]
Here is my **Procfile**:
```ruby
web: unset PORT && bin/rails server
js: yarn build --watch
css: yarn build:css --watch
```
**After running of the command** ```foreman start``` **I get an error**:

21:05:09 web.1  | started with pid 4424
21:05:09 js.1   | started with pid 17484
21:05:09 css.1  | started with pid 7796
21:05:09 web.1  | "unset" �� ���� ����७��� ��� ���譥�
21:05:09 web.1  | ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
21:05:10 web.1  | exited with code 1
21:05:10 system | sending SIGTERM to all processes
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:201:in `kill': Invalid argument (Errno::EINVAL)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:201:in `kill_children'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:473:in `terminate_gracefully'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:439:in `wait_for_shutdown_or_child_termination'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:60:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/cli.rb:42:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/command.rb:27:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor.rb:369:in `dispatch'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/base.rb:444:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/bin/foreman:7:in `<top (required)>'
        from C:/Ruby32-x64/bin/foreman:32:in `load'
        from C:/Ruby32-x64/bin/foreman:32:in `<main>'

**Comment by mikekosulin** [comment]
I had the same issue and resolved it by switching to [hivemind](https://github.com/DarthSim/hivemind).
